config/routes.rb
Agenda2::Application.routes.draw do
  
  scope "api" do
    resources :contacts
  end

  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :cellphone, :email, :presence => true
	validates_format_of     :email,
	                        :with       => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
	                        :message    => ' must be a valid E-mail'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Contact</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :lastname, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :lastname, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :cellphone, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :cellphone, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', contacts_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/contacts/edit.html.erb
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<!-- <h1>Contacts</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.id %></td>
        <td><%= link_to contact.name, contact_path(contact) %></td>
        <td><%= contact.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_contact_path(contact), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', contact_path(contact), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_contact_path, :class => 'btn btn-primary' %> -->

<div class="container-fluid">
    <h1>Contacts</h1>
    <button onclick="location.href = '#contacts/new'" class="btn btn-primary">New Contact</button>
    <br/><br/>
    <div class="row">
       <div class="span12" id="notifications"></div>
    </div>
</div>
<br/>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3" id="contacts">
      <div id="container"></div>
      <!--Sidebar content-->
    </div>
    <div class="span9" id="detail">
      <!--Body content-->
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render :partial => 'form' %>

app/views/contacts/show.html.erb
<h1>/Contact</h1>

<p>
  <b>Name</b><br>
  <%= @contact.name %>
</p>

<p>
  <b>Lastname</b><br>
  <%= @contact.lastname %>
</p>

<p>
  <b>Cellphone</b><br>
  <%= @contact.cellphone %>
</p>

<p>
  <b>Email</b><br>
  <%= @contact.email %>
</p>

<div class="form-actions">
  <%= link_to 'Back', contacts_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_contact_path(@contact), :class => 'btn' %>
  <%= link_to 'Delete', contact_path(@contact), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda2</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Agenda2</a>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= yield %>
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>